/** Generous Event design system tokens — mirrors DESIGN.md */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "var(--color-outline)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "error-container": "var(--color-error-container)",
        background: "var(--color-background)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-dim": "var(--color-surface-dim)",
        "outline-variant": "var(--color-outline-variant)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        error: "var(--color-error)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        secondary: "var(--color-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "primary-container": "var(--color-primary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        surface: "var(--color-surface)",
        "surface-container-high": "var(--color-surface-container-high)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-error": "var(--color-on-error)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-container": "var(--color-tertiary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        primary: "var(--color-primary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary": "var(--color-on-primary)",
        "on-background": "var(--color-on-background)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-bright": "var(--color-surface-bright)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "primary-fixed": "var(--color-primary-fixed)",
        tertiary: "var(--color-tertiary)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
};
